# Convolutional Neural Network

### Importing the libraries

In [22]:
import tensorflow as tf
from keras_preprocessing.image import ImageDataGenerator
import pandas as pd
import numpy as np

In [4]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Preprocessing the Training set

In [24]:
train_set = pd.read_csv('drive/My Drive/dataset/train.csv')

In [6]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)
training_set = train_datagen.flow_from_directory('drive/My Drive/new_dataset/train',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode="categorical")

Found 364 images belonging to 8 classes.


In [47]:
class_labels = training_set.class_indices
print(class_labels)

{'bharatanatyam': 0, 'kathak': 1, 'kathakali': 2, 'kuchipudi': 3, 'manipuri': 4, 'mohiniyattam': 5, 'odissi': 6, 'sattriya': 7}


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


### Preprocessing the Test set

In [66]:
test_set = pd.read_csv('drive/My Drive/dataset/test.csv')

### Compiling the CNN

In [16]:
cnn = tf.keras.models.Sequential()
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=[64, 64, 3]))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))
cnn.add(tf.keras.layers.Flatten())
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))
cnn.add(tf.keras.layers.Dense(units=8, activation='softmax'))

### Training the CNN on the Training set and evaluating it on the Test set

In [18]:
cnn.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
cnn.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 31, 31, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 29, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 6272)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 128)               802944    
_________________________________________________________________
dense_4 (Dense)              (None, 8)                

In [19]:
cnn.fit(x = training_set, epochs = 25)

Epoch 1/25
12/12 [==============================] - 141s 12s/step - loss: 2.0969 - accuracy: 0.1566
Epoch 2/25
12/12 [==============================] - 4s 314ms/step - loss: 1.9695 - accuracy: 0.2582
Epoch 3/25
12/12 [==============================] - 4s 329ms/step - loss: 1.7827 - accuracy: 0.2885
Epoch 4/25
12/12 [==============================] - 4s 321ms/step - loss: 1.6076 - accuracy: 0.4203
Epoch 5/25
12/12 [==============================] - 4s 313ms/step - loss: 1.5103 - accuracy: 0.4423
Epoch 6/25
12/12 [==============================] - 4s 316ms/step - loss: 1.3544 - accuracy: 0.5082
Epoch 7/25
12/12 [==============================] - 4s 311ms/step - loss: 1.2714 - accuracy: 0.5934
Epoch 8/25
12/12 [==============================] - 4s 311ms/step - loss: 1.1184 - accuracy: 0.6016
Epoch 9/25
12/12 [==============================] - 4s 325ms/step - loss: 1.0811 - accuracy: 0.6016
Epoch 10/25
12/12 [==============================] - 4s 313ms/step - loss: 1.0378 - accuracy: 0.6374

In [67]:
import os
for dirname, _, filenames in os.walk('drive/My Drive'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

drive/My Drive/Engineering Maths Hand Written Notes Made Easy.pdf
drive/My Drive/computerscience.pdf
drive/My Drive/Resume (1).doc
drive/My Drive/Web Development_Training_Certificate (1).pdf
drive/My Drive/bbp_resume2.doc
drive/My Drive/New Doc 2018-08-07.pdf
drive/My Drive/Web Development_Training_Certificate.pdf
drive/My Drive/CSIR appli.pdf
drive/My Drive/New Doc 2018-08-07_1.jpg
drive/My Drive/New Doc 2018-08-07_2.jpg
drive/My Drive/IMG_20160218_154510_1.jpg
drive/My Drive/IMG_20160219_180746.jpg
drive/My Drive/IMG_20160225_184439.jpg
drive/My Drive/CandidateHallTicket.pdf
drive/My Drive/New Doc 2018-09-14 21.35.50_4.jpg
drive/My Drive/guntapallavapelmplan.jpg
drive/My Drive/tatayya.mp3
drive/My Drive/thatayya1.mp4
drive/My Drive/IMG_20190119_192624.jpg
drive/My Drive/VID_20190119_184320.mp4
drive/My Drive/IMG_20190119_145956_HHT.jpg
drive/My Drive/VID_20190119_192632.mp4
drive/My Drive/VID_20190119_133936.mp4
drive/My Drive/IMG_20190119_133923_HHT.jpg
drive/My Drive/VID_20190119_1

In [49]:
print(class_labels)
inverse_map={4:'manipuri', 0:'bharatanatyam', 6:'odissi' ,2:'kathakali',1: 'kathak', 7:'sattriya',
 3:'kuchipudi', 5:'mohiniyattam'}

{'bharatanatyam': 0, 'kathak': 1, 'kathakali': 2, 'kuchipudi': 3, 'manipuri': 4, 'mohiniyattam': 5, 'odissi': 6, 'sattriya': 7}


In [68]:
from keras.preprocessing import image
from tqdm import tqdm
import cv2
test_label=[]
path = 'drive/My Drive/dataset/test'
for i in tqdm(test_set["Image"]):
  final_path=os.path.join(path,i)
  img = image.load_img(final_path, target_size = (64, 64))
  img = image.img_to_array(img)
  img = np.expand_dims(img, axis = 0)
  result = cnn.predict(img)
  class_label = inverse_map[np.argmax(result)]
  test_label.append(class_label)
  

100%|██████████| 156/156 [01:31<00:00,  1.70it/s]


In [69]:
np.array(test_label)

array(['sattriya', 'kathakali', 'kuchipudi', 'odissi', 'bharatanatyam',
       'kuchipudi', 'kuchipudi', 'kathakali', 'kuchipudi', 'kuchipudi',
       'sattriya', 'bharatanatyam', 'sattriya', 'sattriya', 'sattriya',
       'bharatanatyam', 'odissi', 'bharatanatyam', 'mohiniyattam',
       'odissi', 'odissi', 'kathakali', 'kathakali', 'mohiniyattam',
       'manipuri', 'kathakali', 'sattriya', 'bharatanatyam', 'odissi',
       'bharatanatyam', 'mohiniyattam', 'odissi', 'manipuri', 'odissi',
       'mohiniyattam', 'bharatanatyam', 'odissi', 'odissi', 'manipuri',
       'sattriya', 'kathakali', 'mohiniyattam', 'odissi', 'mohiniyattam',
       'mohiniyattam', 'mohiniyattam', 'mohiniyattam', 'mohiniyattam',
       'kathakali', 'kuchipudi', 'mohiniyattam', 'kathakali', 'kuchipudi',
       'kuchipudi', 'manipuri', 'kathak', 'bharatanatyam', 'odissi',
       'sattriya', 'sattriya', 'kathakali', 'sattriya', 'sattriya',
       'kuchipudi', 'odissi', 'kuchipudi', 'kathakali', 'odissi',
       'od

In [72]:
submission = pd.DataFrame({ 'Image': test_set['Image'], 'target': test_label })
print(submission.head(10))
submission.to_csv('submission.csv', index=False)

     Image         target
0  508.jpg       sattriya
1  246.jpg      kathakali
2  473.jpg      kuchipudi
3  485.jpg         odissi
4  128.jpg  bharatanatyam
5  410.jpg      kuchipudi
6  465.jpg      kuchipudi
7  196.jpg      kathakali
8  340.jpg      kuchipudi
9  467.jpg      kuchipudi


In [52]:
y_in = cnn.predict(training_set)
label = [np.argmax(i) for i in y_in]
labels = [inverse_map[i] for i in label]
y_pred = np.array(labels)

In [53]:
from sklearn.metrics import f1_score, confusion_matrix
score = f1_score(train_set['target'], y_pred, average = 'weighted')
cm = confusion_matrix(train_set['target'], y_pred)
print(score)
print(cm)

0.11070986513462863
[[ 4  7  4  3  3  6  9 11]
 [ 3  5  7  8  7  7  2  5]
 [ 4  5  5 10  5  8  3  7]
 [10  2  7  5  8  4  6  4]
 [ 4  3  3  7  3  4  7  5]
 [ 6  8 10  7  4  6  5  4]
 [10  5  5  9  3  3  7  7]
 [ 6  1  6  8  6  7  6  5]]


## Part 4 - Making a single prediction

In [58]:
import numpy as np
from keras.preprocessing import image
test_image = image.load_img('drive/My Drive/dataset/train/195.jpg', target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
print(result)
print(inverse_map[np.argmax(result)])

[[0. 0. 1. 0. 0. 0. 0. 0.]]
kathakali


In [64]:
training_set.filenames

['bharatanatyam/113.jpg',
 'bharatanatyam/115.jpg',
 'bharatanatyam/116.jpg',
 'bharatanatyam/117.jpg',
 'bharatanatyam/118.jpg',
 'bharatanatyam/120.jpg',
 'bharatanatyam/121.jpg',
 'bharatanatyam/122.jpg',
 'bharatanatyam/123.jpg',
 'bharatanatyam/124.jpg',
 'bharatanatyam/126.jpg',
 'bharatanatyam/127.jpg',
 'bharatanatyam/130.jpg',
 'bharatanatyam/131.jpg',
 'bharatanatyam/133.jpg',
 'bharatanatyam/134.jpg',
 'bharatanatyam/135.jpg',
 'bharatanatyam/136.jpg',
 'bharatanatyam/137.jpg',
 'bharatanatyam/139.jpg',
 'bharatanatyam/140.jpg',
 'bharatanatyam/141.jpg',
 'bharatanatyam/142.jpg',
 'bharatanatyam/143.jpg',
 'bharatanatyam/144.jpg',
 'bharatanatyam/148.jpg',
 'bharatanatyam/149.jpg',
 'bharatanatyam/151.jpg',
 'bharatanatyam/153.jpg',
 'bharatanatyam/154.jpg',
 'bharatanatyam/155.jpg',
 'bharatanatyam/156.jpg',
 'bharatanatyam/158.jpg',
 'bharatanatyam/159.jpg',
 'bharatanatyam/160.jpg',
 'bharatanatyam/161.jpg',
 'bharatanatyam/163.jpg',
 'bharatanatyam/164.jpg',
 'bharatanat